### ISSUE TITLE
Error "No credential store has been selected" when using multiple credential helpers

### ISSUE THREAD

**Issue by hickford** [git-ecosystem/git-credential-manager#1283]
Git supports [multiple credential helpers](https://git-scm.com/docs/gitcredentials#Documentation/gitcredentials.txt-helper) configured in sequence. I tried the following Git config to use a custom storage helper followed by GCM:

```
[credential]
	helper = storage
	helper = manager
```

But GCM gave me error:

> fatal: No credential store has been selected.

This refers to the choice of GCM's [internal credential store](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md). This error makes sense when GCM is the only Git credential helper, but is superfluous when multiple credential helpers are configured. 

Workaround: effectively disable [GCM's internal credential store](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/credstores.md) by telling it to cache with timeout zero.

```
[credential]
	helper = storage
	helper = manager
	credentialStore = cache
	cacheoptions = --timeout 0
```

**Comment by hickford** [comment]
It would be interesting to undestand any differences in behaviour between typical GCM configuration with subordinate credential store:

```
[credential]
	helper = manager
	credentialStore = cache
```

and using Git with two credential helpers

```
[credential]
	helper = cache
	helper = manager
	credentialStore = cache
	cacheoptions = --timeout 0
```

**Comment by mjcheetham** [comment]
> It would be interesting to understand any differences in behaviour between typical GCM configuration with internal credential store:
> and using GCM as one of multiple Git credential helpers

At least for the macOS Keychain, there are some differences in the actual keychain entry that is used. GCM uses [`kSecClassGenericPassword`](https://developer.apple.com/documentation/security/ksecclassgenericpassword) class for items, whereas `git-credential-osxkeychain` uses [`ksecclassinternetpassword`](https://developer.apple.com/documentation/security/ksecclassinternetpassword) (by virtue of using the [`*InternetPassword` Keychain APIs](https://github.com/git/git/blob/master/contrib/credential/osxkeychain/git-credential-osxkeychain.c#L73).

The other is the identity of the application that is actually reading/writing to the keychain is different. macOS Keychain's ACLs record the specific executable identity that can access those entries:

<img width="646" alt="image" src="https://github.com/git-ecosystem/git-credential-manager/assets/5658207/c6d41b0d-1935-48f4-9f54-cfd0652cb83c">
<img width="646" alt="image" src="https://github.com/git-ecosystem/git-credential-manager/assets/5658207/b5042129-cc25-4a75-a721-c004a280bfbe">

Finally, we preface our credentials with an optional namespace that is user configurable.. defaulting to `git`. So our credentials are stored as `git:<service>` on all platforms by default, whereas `osxkeychain` doesn't prefix (cannot, due to being an internet password class).

**Comment by mjcheetham** [comment]
> This error makes sense when GCM is the only Git credential helper, but is superfluous when multiple credential helpers are configured.

One thing we could consider is adding a `passthrough` option to `credentialStore` that effectively does the same as the `cache` workaround and just acts as a no-op.
