### ISSUE TITLE
Installation script resulted in unintended Fedora upgrade

### ISSUE THREAD

**Issue by JWShaw** [git-ecosystem/git-credential-manager#1298]
Running the `linux-install-source.sh` script resulted in `dnf update -y` being executed, which caused an undesired upgrade from Fedora 36 to Fedora 37 on my machine.  Can we omit the `-y` flag to prevent similar occurrences in the future?

It's also worth noting that, according to the `dnf` manpages, `update` is a deprecated alias for `upgrade`

**Comment by JWShaw** [comment]
I was mistaken about the system upgrade: I was already running Fedora 37, and my packages were just several weeks out of date.

Nonetheless, is the non-interactive flag required/desirable?

**Comment by ldennington** [comment]
Hi @JWShaw - glad to hear that the system upgrade wasn't caused by the script, as that would certainly be unexpected! We purposefully use the non-interactive flag after printing a message at the beginning of the script indicating that we're going to install things and asking the user to accept:

```
This script will download, compile, and install Git Credential Manager to:

    /usr/local/bin

Git Credential Manager is licensed under the MIT License: https://aka.ms/gcm/license
Do you want to continue? [Y/n] 
```

If you have thoughts for improvement on the message or would like to help transition us away from the deprecated `upgrade` command, we'd welcome a PR! You can find the script [here](https://github.com/git-ecosystem/git-credential-manager/blob/main/src/linux/Packaging.Linux/install-from-source.sh) if you're interested.
