### ISSUE TITLE
how to change the installation directory when installing from source

### ISSUE THREAD

**Issue by AnonymousAccount6688** [git-ecosystem/git-credential-manager#1304]
I don't have the root permission, so I tried to install from source. I used the command sh install-from-source.sh. 

However, it always install to the directory /usr/local/bin, which I cannot since I don't have the permission to write file into the directory.

Is there a way, like --prefix= to change the installation directory to my home directory?

**Comment by ldennington** [comment]
There is currently no way to change the install location since `usr/local/bin` is the standard place for non-system binaries to be installed on Linux. However, we would be open to a community contribution for this feature. [Here is the script](https://github.com/git-ecosystem/git-credential-manager/blob/main/src/linux/Packaging.Linux/install-from-source.sh) if you are interested in making that change!
