### ISSUE TITLE
Microsoft Account user model on Windows.

### ISSUE THREAD

**Issue by MSamWils** [git-ecosystem/git-credential-manager#1355]
Hi @vtbassmatt , @wolf99 , @mjcheetham , I would like to learn more about what's the reason you mentioned this notes in the [windows-broker.md](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/windows-broker.md#for-microsoft-accounts):
 

> Two very important things to note:
>   
>   If you haven't connected any Microsoft accounts to Windows before, the first account you connect will cause the local Windows user account to be converted to a connected account.
>   In addition, you can't change the usage preference for the first Microsoft account connected to Windows: all Microsoft apps will be able to sign you in with that account.
>   As far as we can tell, there are no workarounds for either of these behaviors (other than to not use the WAM broker).

I believe there are some misunderstandings about how MSA works in WAM as well as SSO.
By adding the MSA via application such as GCM, the MSA can be added as associated (SSO) or secondary (CSO, one click sign on) and it's controlled by user.
In addition, it should not convert your local account into MSA. 

Please let me know what's your experience and the reason behind those notes that you have added.
Thanks.

**Comment by ldennington** [comment]
Hey @MSamWils - I just set up a new Windows machine to test this and believe I have experienced both of these behaviors. Illustrating with screenshots:

1. I am signed in under the **User** local account.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/11321782/68d2ead9-01e0-4c4c-bc56-c72eab3bbb37)

2. I navigated to **Accounts** > **Email & accounts** and clicked **Add a Microsoft account**. Note that I am still signed in as **User**

![image](https://github.com/git-ecosystem/git-credential-manager/assets/11321782/912ec641-51e0-4681-b55b-b800fa93b44f)

3. I navigated the prompts to sign in with one of my MSA accounts and clicked **Sign in**.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/11321782/2b4e64c9-8afe-4996-a962-bd2b9b1749a5)

4. I clicked **Next** when prompted to **Use this account everywhere on your device**.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/11321782/1142724e-7ccf-4f05-b1d7-9d43adf85212)

5. The **User** account was converted to my **MSA** account.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/11321782/1fd48468-79d3-423c-822b-6f14a200d416)

6. Additionally, when I clicked the carat next to my MSA account no usage preferences were provided.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/11321782/eef30cde-d328-44ed-a857-5955c684e814)

7. I went through steps 2-4 again to add a second MSA account. When I clicked the carat next to the new account, I was given the option to select usage preferences.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/11321782/fdb67396-2c01-4bed-8d76-0d5a2d3ea7ba)

Closing this issue, since details about the experience have been provided as requested.

**Comment by MSamWils** [comment]
Hi @ldennington, that's correct but this didn't affect how you unlock the machine. 
You are still using your local account credential to unlock.

In addition, user can choose "Microsoft apps only" instead of clicking the "next" button which it will be one click sign on.

My point is that both notes that you mentioned are incorrect and there is a workaround for that.

**Comment by mjcheetham** [comment]
> Hi @ldennington, that's correct but this didn't affect how you unlock the machine.
> The local account didn't convert into the MSA and you are still using your local account credential to unlock the machine.

The document does not say anything about the process changing how the machine is unlocked. It says:

> [..] will cause the local Windows user account to be converted to a connected account.

After signing-in with an MSA this way, the local account becomes a connected account; "associated (SSO)" in your parlance, and cannot be 'un-associated'. This part is still correct.

> In addition, user can choose "Microsoft apps only" instead of clicking the "next" button which it will be one click sign on, which is different with SSO.

I guess you are technically correct here! Thanks for pointing out that this is an available option. We can make a small edit to our wording here to clarify the difference between the default "next" option, and the "Microsoft Apps only" link (which seemingly has been renamed to "Just this app" in newer Windows 11 builds - it's hard to keep up with all the UI changes here! 😅 ).

![image](https://github.com/git-ecosystem/git-credential-manager/assets/5658207/d4ec7ce2-4f9f-4060-ae2f-afeb5d846bd0)


The purpose of this document is to raise these concerns to users before they enable WAM. The subtle differences in the behaviour of the different options/buttons/links is a dark pattern that we do not want to encourage.

**Comment by MSamWils** [comment]
Thanks for the response @mjcheetham .

My goal is to make sure we unblock all the issues as well as address all the concerns when enabling WAM broker in order to make our customer secure. So if there are any feedback, concerns regarding to enabling WAM broker, please let me know so that we can address those and improve our product.
 
> the local Windows user account to be converted to a connected account.

The word "converted" means that your local account is being replaced by the MSA. However, by associating MSA in Windows, it is only enabling SSO but not replacing the local account. The LSA, account profile and the lock screen are still showing the local account name, not the MSA. 
In addition, the associated MSA can be dis-associated by clicking "Stop signing in to all Microsoft apps automatically" under Settings -> Accounts -> Your info page.

**Comment by mjcheetham** [comment]
Thanks for the pointers and context here @MSamWils. We've now updated the document to reflect the different behaviours between these connected and associated accounts, and how to remove them from SSO with the local Windows user.

You can see the latest version here: https://gh.io/gcm/wam
