### ISSUE TITLE
Regression: credential.namespace no longer retrieves cached credentials in namespaces from Windows Credential Manager

### ISSUE THREAD

**Issue by dmealo** [git-ecosystem/git-credential-manager#1382]
### Version

2.2.2

### Operating system

Windows

### OS version or distribution

Windows 11 Pro

### Git hosting provider(s)

GitHub, GitHub Enterprise Server

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I have been using GCM's [credential.namespace](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/configuration.md#credentialnamespace) feature to allow connection to multiple GitHub accounts on one device (one on github.com and one on GHEC in particular) without issue in version 2.0.886+ea93cb5158. So cloning the first repo with a previously unused credential.namespace value would trigger a GitHub login dialog and then credentials would be loaded by GCM automatically for any repo in that same namespace and this worked great!

### Actual behavior

After updating to v2.2.2 has caused a regression of this functionality. I am now prompted every time for Git operations that are using a credential.namespace configuration on 3/4 of repos on two different machines - one that I upgraded just to repo the issue. After each prompt, the Git operation functions, so I know that it is not an authentication or permissions issue, but seems like GCM is not seeing that it already has the credentials for that namespace in the Windows Credential Manager.

### Logs

[git credential manager.credential.namespace.regression between 2.0.886+ea93cb5158 and 2.2.2.log](https://github.com/git-ecosystem/git-credential-manager/files/12365076/git.credential.manager.credential.namespace.regression.between.2.0.886%2Bea93cb5158.and.2.2.2.log)
[gcm-diagnose.log](https://github.com/git-ecosystem/git-credential-manager/files/12365138/gcm-diagnose.log)

**Comment by dmealo** [comment]
I should add that I am choosing the Use Code method and authenticating via https://github.com/login/device since Use Browser method results in connection issue at the loopback address with a special port number (on two machines).

Also, I just verified that downgrading GCM to 2.0.886 immediately resolves the issue without even needing to flush credentials or reauthenticate - just a simple Git operation tests correctly with no other changes or restarts, etc (though it was in a new terminal session by coincidence).

**Comment by mjcheetham** [comment]
Hello @dmealo,

When you say "one on GHEC" do you know if you are using [Enterprise Managed Users (EMU)](https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-enterprise-managed-users-for-iam/about-enterprise-managed-users)?

From your logs (thanks for including!) I can see this:

```text
22:51:46.029340 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
22:51:46.044920 ...bHostProvider.cs:142 trace: [GetCredentialAsync] Found 1 accounts in the store for service=https://github.com:
22:51:46.044920 ...bHostProvider.cs:145 trace: [GetCredentialAsync]   david-<redacted>_<redacted>
22:51:46.045918 ...bHostProvider.cs:218 trace: [FilterAccounts] Account filtering is enabled.
22:51:46.048929 ...bHostProvider.cs:226 trace: [FilterAccounts] Filtering based on WWW-Authenticate header information...
22:51:46.050128 ...bHostProvider.cs:229 trace: [FilterAccounts] Matched 0 accounts with public domain:
22:51:46.050706 ...bHostProvider.cs:181 trace: [GetCredentialAsync] No existing credentials found.
```

User handles in the form `xxxx_yyyy` are typically EMUs, which is why I ask.

If you are an EMU, do you know if you have the "Automatically redirect users to sign in" setting enabled or not?

You'd get to this from the Enterprise settings page:
Settings > Authentication security > Single sign-on settings > Automatically redirect users to sign in.

![image](https://github.com/git-ecosystem/git-credential-manager/assets/5658207/ab7c7a7d-63f8-421d-a288-4c9aedb891a8)

This setting, when checked ✅, will cause the server to provide hints to GCM that the remote needs a user from the correct enterprise. Without it, we can only assume this is a _public_ account, and so filter out any accounts that look like an EMU (`xxxx_yyyy`).

**Comment by dmealo** [comment]
Thanks for your reply! 

Yes, it is an EMU account on GHEC. I will have to check with IT on that setting. I will report what I find. Ideally, I want that checked or not checked? Is that a change in behavior sine version 2.0.886 that took place then?

**Comment by mjcheetham** [comment]
> Ideally, I want that checked or not checked?

If you check this setting, then GCM will start getting 'hints' that allow it to correctly select and recall the correct credentials. This setting also controls whether or not, in the web, if you visit an org or repository and you're not logged in then you get automatically redirected to your companies identity provider to sign in.

> Is that a change in behavior sine version 2.0.886 that took place then?

In GCM 2.2.x we [added support](https://github.com/git-ecosystem/git-credential-manager/pull/1190) for EMU account filtering, to try and automatically select and differentiate between 'public' and EMU accounts - so that you can be signed in to both at the same time.

Unfortunately if this 'auto SSO' setting is disabled, we are unable to differentiate between a public and EMU account. We hope to fix this in the future.

If you are unable to get that setting enabled, for now, you can disable this filtering locally in GCM by setting:

```shell
git config --global credential.gitHubAccountFiltering "false"
```

Documentation:  https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/configuration.md#credentialgithubaccountfiltering

**Comment by dmealo** [comment]
@mjcheetham, Thanks for explaining all of that. That's a great feature the team has added. However, unfortunately our team does not have that setting enabled, but I'm working with them to see if it can be in the future. I can also say that I've successfully used your suggestion to disabled gitHubAccountFiltering in GCM v.2.3.2 to resolve the issue I was having at the outset of this Issue, so thank you for that solution and I will now close this.
