### ISSUE TITLE
GCM Account Filtering and Storage

### ISSUE THREAD

**Issue by byjrack** [git-ecosystem/git-credential-manager#1387]
### Version

2.2.2

### Operating system

Windows

### OS version or distribution

11 22h2

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

GCM to request creds, Store, and then reuse

### Actual behavior

Worked around using https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/configuration.md#credentialgitHubAccountFiltering and false.

We have a number of users who are only EMU and going to our Enterprise Orgs and for an unknown reason the filtering seems to filter out the stored creds resulting in them always being asked.

In the output it finds the EMU user_enterprise account, but then it does the "Filtering based on WWW-Authenticate header info" step and then it notes "matched 0 accounts with public domain" so it goes no existing credentials found.

Even after entry again (Token or Browser) the credential in Windows Credentials seems to be updated, but GCM will still filter it out.  What is actually happening with that wwwauth filter?  In the log it mentions realm=Github so bit of a head scratcher?

**Comment by ldennington** [comment]
I believe [this](https://github.com/git-ecosystem/git-credential-manager/issues/1382#issuecomment-1682624623) will resolve your issue - enabling the **Automatically redirect users to sign in** enterprise-wide setting is ideal, but if that is not possible, [this config workaround](https://github.com/git-ecosystem/git-credential-manager/issues/1382#issuecomment-1683045756) should work. We apologize for the inconvenience - we hope to fix this in the near future.

**Comment by byjrack** [comment]
We are already using the filtering=false workaround for the moment.

Ok so the real fix is the redirect vs 404.  I know we were waiting for that feature to make it out of testing, but didn't know it was ga yet.  Good to know how it all comes together.  It would be great to have some more detailed docs on how it all works if possible.

**Comment by ldennington** [comment]
I don't know that there are any official GitHub docs available on this. However, I can share that the behavior is due to the server by default not providing any of the hints (in the `WWW-Authenticate` header) that are needed to use an EMU account to authenticate for the particular Git repo. The reference you made above ("matched 0 accounts with public domain") indicated that GCM was filtering for public accounts only (i.e. not EMU) until you used the config to turn off filtering.

Although they're not docs, reading through the following should shed some light on your original question of how this all works:

1. @mjcheetham's [patch series](https://lore.kernel.org/git/pull.1352.git.1663097156.gitgitgadget@gmail.com/) to add the ability to interpret `WWW-Authenticate` headers to Git may shed some light on your original question on how this works.
2. @mjcheetham's [EMU PR in GCM](https://github.com/git-ecosystem/git-credential-manager/pull/1190).

**Comment by byjrack** [comment]
Yeah I think the missing part was that the hints only get appended to the header if the Enterprise 404 handling is enabled.  I don't know if Github will just add those by default to EMU targets, but we are looking at that Enterprise flag anyways because of the deep link user experience improvement.  Hopefully we can avoid having associates adjusting the filtering as it just becomes config cruft.
