### ISSUE TITLE
fatal: credential url cannot be parsed

### ISSUE THREAD

**Issue by jgedri** [git-ecosystem/git-credential-manager#1394]
I'm trying to push to a remote and getting the following error.

```
warning: url has no scheme: azrepos:org/<organization>
fatal: credential url cannot be parsed: azrepos:org/<organization>

git version 2.25.1
git credential-manager 2.2.2
Ubuntu 20.04.6 LTS

hub     https://github.com/jgedri/dragon-game.git (fetch)
hub     https://github.com/jgedri/dragon-game.git (push)
origin  https://spiritsoft@dev.azure.com/spiritsoft/DragonRuby%20games/_git/DragonRuby%20games (fetch)
origin  https://spiritsoft@dev.azure.com/spiritsoft/DragonRuby%20games/_git/DragonRuby%20games (push)
```

**Comment by mjcheetham** [comment]
Hello @jgedri please can you complete the bug template including all required information. Without this we cannot investigate.

---

**GCM and Git versions:**

`git --version`
`git credential-manager --version`

**Operating system and version:**

**Git host/remote URL:**

`git remote -vv`

**Logs:**

You can enable trace logging by setting both the `GIT_TRACE` and `GCM_TRACE` environment variables to `1` and include the output from your terminal.

**Comment by jgedri** [comment]
What do the environment variables look like?

**Comment by ldennington** [comment]
@jgedri - please set both `GIT_TRACE=1` and `GCM_TRACE=1`.

**Comment by ldennington** [comment]
Closing due to lack of response.

**Comment by DaveyBiggers** [comment]
I had the same problem, on the same version of git (2.25.1)

I updated git like this:
```
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git
```
Now (version 2.45.1) the problem has gone away.

FWIW I believe the problem was related to this fix: https://github.com/git/git/blob/master/Documentation/RelNotes/2.17.5.txt - which prevented git from working with "under-specified credential patterns". I think this was probably relaxed again later (here https://github.com/git/git/commit/6828e5972b82f474cc14ca9cb9e01e897f205f4c maybe?) hence updating git solved it for me.

**Comment by jkapil** [comment]
git --version
git version 2.25.1
git credential-manager --version
2.4.1
git remote -vv
origin  https://<redacted>.visualstudio.com/<redacted>/_git/<redacted> (fetch)
origin  https://<redacted>.visualstudio.com/<redacted>/_git/<redacted> (push)

I am getting same error.

**Comment by jkapil** [comment]
@ldennington  I think, the issue can be reopened now. Relevant information about version is provided.

**Comment by dscho** [comment]
> git version 2.25.1

@jkapil please have a look at https://github.com/git-ecosystem/git-credential-manager/issues/1394#issuecomment-2117789619 that reported that an update from that version to v2.45.1 addressed the problem, indicating that your version is too old.

You will want to update in any case because there have been _several_ security bug-fix releases published in the meantime; You're using an insecure version of Git.
