### ISSUE TITLE
BUG: Attempting to authenticate on a Gist repo returns a 404

### ISSUE THREAD

**Issue by danawoodman** [git-ecosystem/git-credential-manager#1401]
It appears auth via does not work for Github Gists?

Repo

- Clone a gist
- Commit a change
- `git push`
- Popup showing login options show, hit `Sign in with your browser`
- End up at a 404 page

![image](https://github.com/git-ecosystem/git-credential-manager/assets/157695/1540557f-900a-449c-bede-db5190dadb43)

URL:

```
https://gist.github.com/login/oauth/authorize?response_type=code&client_id=...&state=...&code_challenge_method=S256&code_challenge=...&redirect_uri=http%3a%2f%2flocalhost%3a54138%2f&scope=repo+gist+workflow
```

**Comment by mjcheetham** [comment]
Thanks for spotting and reporting this issue! We've merged in a fix for this, which will be available in the next release of GCM.

In the meantime, one workaround would be to first authenticate with https://github.com, rather than a Gist (https://gist.github.com), and then Gist operations should work thereafter.

You can either perform a clone of a regular Git repo on GitHub, or run `git credential-manager github login` explicitly.

**Comment by danawoodman** [comment]
Nice thanks for the quick fix! I got around it but figured I'd report either way
