### ISSUE TITLE
Git credential manager keeps popping up and shows multiple popups at a time

### ISSUE THREAD

**Issue by smaillet-ms** [git-ecosystem/git-credential-manager#1425]
### Version

2.3.2

### Operating system

Windows

### OS version or distribution

Windows 11 22H2 22621.2361

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}.visualstudio.com

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I can use git without being nagged by pop-ups all the time. 

### Actual behavior

randomly pops up dialog to allow it to use my current credentials EVEN WHEN NOT DOING ANYTHING WITH GIT! (if it has them why is it asking me again , and again , and again... - I said yes - get over it and use them damn it!)

See also: #1411 and #1415 (First was closed as a dup of the second, and second was closed with use of PAT) but neither is actually resolved yet for me. I've used the command to set the PAT as described in #1415 but it doesn't make any difference.

Please don't close this issue or anything you elect to dup it to without confirming with me that the problem is resolved. Having to fill in multiple bugs from the same issue is a major PITA (GitHub provides no options for the bug creator or anyone else from re-opening or de-duplicating bugs)

**Comment by ckegley** [comment]
This has also been happening to me ever since I updated to use MFA.

**Comment by Peetee06** [comment]
This issue has started popping up today for me as well. Git Credentials Manager keeps randomly popping up. Probably triggered by VS Code fetching regularly in the background. I can't remember having changed anything on GitHub.

**Comment by ldennington** [comment]
@smaillet-ms - the original issue was duped because the creator of #1415 included logs, which make it much easier for maintainers to diagnose and resolve problems. Since logs were not included in #1411, we used the information we had (that you were using Azure DevOps and the Windows Broker and experiencing issues with unsolicited prompts) when making the decision to dupe.

As @Peetee06 stated, a potential cause of the repeated prompts is the configuration of your IDE. For example, Visual Studio Code has an [`autofetch` setting](https://code.visualstudio.com/docs/sourcecontrol/overview#_remotes) that will trigger periodic fetches from remotes.

The logs requested in [the issue template](https://github.com/git-ecosystem/git-credential-manager/issues/new?template=auth-issue.yml) would be incredibly helpful for the maintainers to resolve this issue. The personal information you would want to redact would be things like your username and your Azure DevOps org/repo name. However, I realize you may be unable to provide logs based on your reasons in #1411. In light of this, I may be able to gain some information if you include the output of the following commands in your response:

`git-credential-manager diagnose`
`git config --list --show-origin`

**Note:** You may need to navigate into `%PROGRAM FILES%\Git\mingw64\bin` to run the above commands if GCM is not on your path.

Finally, I realize you are frustrated, and I'm sorry about that. However, please try to refrain from using inflammatory language in the GCM repository, as it goes against our [Code of Conduct](https://github.com/git-ecosystem/git-credential-manager/blob/main/CODE_OF_CONDUCT.md).

**Comment by ldennington** [comment]
Closing - no response in 3 weeks.

**Comment by DeveloperPaul123** [comment]
I also had this issue but it was due to Visual Studio's Git integration features. I turned this off and the pop-ups stopped. Just wanted to post this here in case anyone else comes across this issue.
