### ISSUE TITLE
Error viewing documentation

### ISSUE THREAD

**Issue by mbtools** [git-ecosystem/git-credential-manager#1517]
I installed `git 2.43.0` from https://www.git-scm.com/downloads. When running `git credential-manager --help`, the doc file is not found:

```
PS C:\GitHub> git credential-manager --version
2.4.1
PS C:\GitHub> git credential-manager --help
fatal: 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-credential-manager.html': documentation file not found.
```

Indeed, `git-credential-manager.html` does not exist. Maybe it should be `gitcredentials.html`?

**Comment by dscho** [comment]
Indeed, the documentation is not there. It's in `C:/Program Files/Git/mingw64/doc/git-credential-manager/README.md`, which is not even in HTML format but in Markdown instead.

This should probably be fixed in https://github.com/git-for-windows/build-extra/blob/HEAD/mingw-w64-git-credential-manager/PKGBUILD: The `markdown` package needs to be added as build-time dependency, and then the file should be rendered using `markdown` into the path indicated in the report, using `${pkgdir}` as the relative root directory instead of `C:/Program Files/Git`.

**Comment by dscho** [comment]
Hmm. I could not move the ticket to `git-for-windows/git`, probably some ownership issue. I will close it here because it is a packaging issue with Git for Windows, not a Git Credential Manager bug.

**Comment by mbtools** [comment]
What are the chances that I saw this today? and thought that avatar looks familiar? 🤯 

![image](https://github.com/git-ecosystem/git-credential-manager/assets/59966492/97733674-73db-46b5-bab0-7d312eaab955)

Apparently you contributed to [Gource](https://github.com/acaudwell/Gource) some decades ago... 😀

**Comment by dscho** [comment]
> What are the chances that I saw this today? and thought that avatar looks familiar? 🤯

😆 

> Apparently you contributed to [Gource](https://github.com/acaudwell/Gource) over a decade ago... 😀

Yep, I taught it to use FFMPEG to write to a file.
