### ISSUE TITLE
How to push? I do not have authenticating token. How does this work???

### ISSUE THREAD

**Issue by jcanajr** [git-ecosystem/git-credential-manager#1519]
### Version

---

### Operating system

macOS

### OS version or distribution

N/a

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Doing development environment. I can not push. Something in regards to token. Need instruciotns.

### Actual behavior

help 

### Logs

Help

**Comment by dscho** [comment]
> Something in regards to token.

This is very vague. Could you take a screenshot, at least, and paste it here? Otherwise the only answer anyone competent could give would be along the lines of "_something_ might fix it"...

**Comment by jcanajr** [comment]
I get this message.

please see
https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls
for information on currently recommended modes of authentication.

fatal: Authentication failed for

**Comment by mjcheetham** [comment]
In order to push to a repository, or fetch from a private repository, Git needs a set of credentials to authenticate the request. Git can use its own custom protocol, SSH, or HTTP(S) to communicate to a remote server.

For HTTP-based remote connections, Git only [^1] knows about username and passwords, and can use small programs or scripts called 'credential helpers' to help store and manage these credentials.

GitHub no [longer supports using your username and password](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/) to authenticate over HTTP(S), and requires that you use a personal access token instead.

Git Credential Manager is a Git credential helper that can speak with GitHub to help create and store access tokens for use with Git.

[^1]: Git can also use SPNEGO (such as Kerberos or NTLM on Windows) for HTTP(S)
