### ISSUE TITLE
Change redirect URI from localhost to 127.0.0.1

### ISSUE THREAD

**Issue by hickford** [git-ecosystem/git-credential-manager#594]
The OAuth spec https://datatracker.ietf.org/doc/html/rfc8252#section-8.3 recommends to use 127.0.0.1 instead of localhost:

>  While redirect URIs using localhost (i.e., "http://localhost:{port}/{path}") function similarly to loopback IP redirects described in Section 7.3, the use of localhost is NOT RECOMMENDED.  Specifying a redirect URI with the loopback IP literal rather than localhost avoids inadvertently listening on network interfaces other than the loopback interface.  It is also less susceptible to client-side firewalls and misconfigured host name resolution on the user's device.

Examples in code -- BitBucket, GitHub, Azure https://github.com/GitCredentialManager/git-credential-manager/search?q=localhost

**Comment by hickford** [comment]
NB. This would require changing the redirect URI in the OAuth app settings on GitHub etc. https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls

Since GitHub allows at most one URI, I can't see how to do this in a backwards compatible way.

**Comment by mislav** [comment]
For GitHub, instead of redirecting back to either `127.0.0.1` or `localhost`, GCM should switch to implementing the [Device Authorization Flow](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#device-flow).

The benefits are that the completed browser flow does not have to redirect to any particular URL (and thus GCM doesn't have to spawn a web server at localhost), and the user is able to complete the browser flow on a different machine than the one where GCM is running as a process.

**Comment by hickford** [comment]
GCM already supports OAuth Device Authorization Grant for GitHub . You can configure a preference with [credential.gitHubAuthModes](https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/configuration.md#credentialgithubauthmodes).

**Comment by mislav** [comment]
@hickford Thanks for the info! I was able to opt into Device flow by doing this:
```
git config --global credential.gitHubAuthModes device
```
My next question is, why hasn't GCM auto-detected this when authorizing a git operation from `https://github.com`, but instead it defaulted to OAuth web app flow? I would argue that the Device flow should be the default and that it's straightforward to feature-detect.

**Comment by hickford** [comment]
@mislav what version are you using? https://github.com/GitCredentialManager/git-credential-manager/pull/478 "Add explicit GitHub device code authentication option" so make sure you are using https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.567 or later

My Raspberry Pi has an older version "2.0.498+7ad55fb809"

**Comment by mislav** [comment]
@hickford I have 2.0.632+478753bbb7 and I do see that my version supports the explicit option of choosing Device flow (as per my previous comment). At the risk of derailing the original topic in this thread, my question is whether I should expect that Device flow is auto-detected as a default authentication method for GitHub.com (i.e. taking precedence over web app flow). Should I open another thread to ask this in?

**Comment by hickford** [comment]
@mislav Good idea. On a desktop machine I get the following choice:

```
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Device code
  3. Personal access token
```

**Comment by mislav** [comment]
> Whether you see the 'web browser' option depends on the DISPLAY environment variable

Ah, I see! DISPLAY isn't set for me on macOS, where I would guess that this variable is never set by default. Nevertheless, I think that maybe GCM could assume that macOS always has desktop capability, since it should be pretty uncommon that developers run macOS in headless mode.

Going back to the original topic: in GitHub CLI, which also used to authorize over OAuth web application flow, we've migrated from `http://localhost` callback to `http://127.0.0.1` in a way that's backwards-compatible, using the same OAuth app. This relied on a feature that's not public. If you'd want help with that, I'm sure we could extend feature to your OAuth app as well: just email me at mislav@github.com.

However, it's even a better idea to default to device flow whenever possible instead of the web application flow. That's why I was talking so much about device flow in this thread; sure, you could spend time improving the HTTP redirect experience, but a much better long-term solution is to avoid the local server redirect altogether.

**Comment by mjcheetham** [comment]
The `main` branch and OAuth app registration have both been updated with the new `127.0.0.1` redirect URI (also maintaining the existing `localhost` URI for older clients).

The next release of GCM will now be using the IP loopback address!
